// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuWWsZmOVhB6v02n7GaQP_3BArOGF2pNc',
    appId: '1:87939603137:web:65470d86bf5d6e38a35240',
    messagingSenderId: '87939603137',
    projectId: 'inanceapp',
    authDomain: 'inanceapp.firebaseapp.com',
    storageBucket: 'inanceapp.firebasestorage.app',
    measurementId: 'G-HQ4NQDSPPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Ts-wrU2m9H_rKeHF1JmPoIqeIUvvMc4',
    appId: '1:87939603137:android:4e6605d1cf2312aba35240',
    messagingSenderId: '87939603137',
    projectId: 'inanceapp',
    storageBucket: 'inanceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5V84oWgUS9E9J2yJwOawFCcWUg3wkshc',
    appId: '1:87939603137:ios:59e4168728457527a35240',
    messagingSenderId: '87939603137',
    projectId: 'inanceapp',
    storageBucket: 'inanceapp.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5V84oWgUS9E9J2yJwOawFCcWUg3wkshc',
    appId: '1:87939603137:ios:59e4168728457527a35240',
    messagingSenderId: '87939603137',
    projectId: 'inanceapp',
    storageBucket: 'inanceapp.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuWWsZmOVhB6v02n7GaQP_3BArOGF2pNc',
    appId: '1:87939603137:web:59787feb9b03d582a35240',
    messagingSenderId: '87939603137',
    projectId: 'inanceapp',
    authDomain: 'inanceapp.firebaseapp.com',
    storageBucket: 'inanceapp.firebasestorage.app',
    measurementId: 'G-5WK3S5H9KN',
  );
}
